### PR TITLE
Enhance the logic for showing the hover popup

### PR DESCRIPTION
**Pull request by joelhock**
The current getType call does not return useful information for
member functions.  getDoc returns the most useful info, for
things that have documentation, but nothing for things that
do not.  Next we try to find an exact completion for the
identifier and use its signature.  getType is appropriate
for the remaining cases.

This also adds the available documentation to the completion help.

### CODE REVIEW

**Comment by joelhock** [comment]
hmm, i'm not familiar enough with typings to know what to do to fix the travis build.  would you usually commit the typings change first and then update client/typings.json to point to that revision?

**Comment by agauniyal** [comment]
Looking forward to see this merged!

**Comment by agauniyal** [comment]
ping!

**Comment by richard1122** [comment]
Thanks for your PR. I 've tried and this works perfect.
Also I rebased and fixed some problems with typings. Now we don't need to commit typings first.

Thanks again, I will release new version ASAP.

**Pull request merged**
